//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvMan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class VersionManagerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static VersionManagerSettings defaultInstance = ((VersionManagerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VersionManagerSettings())));
        
        public static VersionManagerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://env-man.sourceforge.net/")]
        public string WebPath {
            get {
                return ((string)(this["WebPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EnvMan.Release")]
        public string VersionFile {
            get {
                return ((string)(this["VersionFile"]));
            }
        }
    }
}
